## Append samples of your project ##
resources:
- core_v1alpha1_securitybaseline.yaml
- core_v1alpha1_workloadpolicy.yaml
- core_v1alpha1_telemetryprofile.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
